export default {
    START_FETCH_CAPSULE_LIST:'START_FETCH_CAPSULE_LIST',              //开始请求
    FETCH_CAPSULE_LIST_SUCCESS:'FETCH_CAPSULE_LIST_SUCCESS',          // 请求成功
    FETCH_CAPSULE_LIST_FAILED:'FETCH_CAPSULE_LIST_FAILED',            // 请求失败
    // CHNAGE_BLOG_LOADING:'CHNAGE_BLOG-LOADING',
}